before_script: 
    - python3 ./gitlab-ci/prepare_to_run_tests.py ~/oge_build_root/

test:
    script: 
      - cd ~/oge_build_root/osate2-core/osate.releng/
      - vncserver :42 -localhost -nolisten tcp
      - DISPLAY=:42.0
      - export DISPLAY
      - mvn -Plocal -fae -Dtest=CreateConnectionTest integration-test
      - vncserver -kill :42
